Add generic type annotation to load tapes
ServiceNow/TapeAgents pull request #107
Opened 2024-11-21 16:04 UTC by gabrielhuang

With this fix, the returned type annotation of load_tapes matches the first argument. Otherwise, it would be annotated as generic Tape type.

``` tapes: list[FormFillerTape] = load_tapes(FormFillerTape, input_dialogues_path)```

2024-11-25 14:05 UTC, ollmer requested changes
Great addition, thanks! We already have such typevar defined in https://github.com/ServiceNow/TapeAgents/blob/main/tapeagents/core.py#L197, let's reuse it in the io.py and merge this way.

2024-11-30 03:09 UTC, rizar commented
@gabrielhuang do you intend to finish this PR?

2024-12-02 16:02 UTC, ollmer approved these changes

2024-12-02 16:03 UTC, ollmer commented
@gabrielhuang said he's ok if I proceed with fixing and merging it.

2024-12-02 16:16 UTC, merged