Switch from conda to uv
ServiceNow/TapeAgents pull request #157
Opened 2024-12-31 22:47 UTC by jpt-sn

uv manages our dev and 2 optional dependencies.

Simply run:
`uv sync` (create a .venv and install requirements in pyproject.toml)
`uv run -m ...` (like python -m ...)

This will make easy to update dependencies:
- `uv pip list --outdated`
- `uv sync --upgrade`
- `uv tree`

The pyproject.toml was updated using these commands (and then manually relaxing versioning):
- `uv add -r requirements.txt`
- `uv add -r requirements.dev.txt --dev`
- `uv add -r requirements.converters.txt --optional converters`
- `uv add -r requirements.finetune.txt --optional finetune`

TODO: 
- [ ] uv build
- [ ] uv publish

2025-01-02 11:13 UTC, ollmer commented on pyproject.toml
> +[dependency-groups]
why are some requirements lists translated to `dependency-groups` and some to `project.optional-dependencies`?

2025-01-02 14:35 UTC, jpt-sn commented on pyproject.toml
> +[dependency-groups]
- [project.dependencies](https://docs.astral.sh/uv/concepts/projects/dependencies/#project-dependencies): Published dependencies.
- [project.optional-dependencies](https://docs.astral.sh/uv/concepts/projects/dependencies/#optional-dependencies): Published optional dependencies, or "**extras**".
- [dependency-groups](https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups): Local dependencies for **development**.

2025-01-21 11:44 UTC, ollmer commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
Let's stick with LTS versions as they are more stable. 22.04 or 24.04 would do.

2025-01-21 11:49 UTC, ollmer commented on README.md
> +2. Create `.venv` environment and install the package in editable mode inside the environment:
can we mention a specific uv command to do that here?

2025-01-21 11:50 UTC, ollmer commented on examples/optimize/requirements.txt
> -dspy-ai==2.4.10
Do we still have this dependency somewhere?

2025-01-21 11:51 UTC, ollmer commented on examples/rl_gsm8k/requirements.txt
> -vllm==0.6.3
Same question, where does this dependency go?

2025-01-21 11:51 UTC, ollmer commented on pyproject.toml
> +  "dspy-ai~=2.4",
ah i see

2025-01-21 11:53 UTC, ollmer commented
Let's update the base image for CI actions and we're good to go.

2025-01-21 12:23 UTC, ollmer requested changes
Let's update the base image for CI actions and we're good to go.

2025-01-21 14:48 UTC, jpt-sn commented on examples/rl_gsm8k/requirements.txt
> -vllm==0.6.3
Under the optional dependency group "finetune"

2025-01-21 14:49 UTC, jpt-sn commented on examples/optimize/requirements.txt
> -dspy-ai==2.4.10
I put it in the dev for now as it is only for one optimization example, maybe finetune optional group would be better. Not convinced yet!

2025-01-21 14:59 UTC, jpt-sn commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
GitHub Hosted Runners images `-latest` are always LTS versions.

> The -latest runner images are the latest stable images that GitHub provides, and might not be the most recent version of the operating system available from the operating system vendor.
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

It's good practice to keep cicd image up-to-date, except if you have complex build, which we don't. Also, GitHub provides annotation on the jobs to announce update to LTS which link to an issue having all necessary details of the changes (see image) https://github.com/actions/runner-images/issues/10636

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/58043376-b069-472a-96de-bf7de03bbb73" />

2025-01-21 15:09 UTC, ollmer commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
Oh, I didn't know that, that's good.

2025-01-21 15:10 UTC, ollmer commented on examples/optimize/requirements.txt
> -dspy-ai==2.4.10
Lets leave in dev for now, ok

2025-01-21 16:22 UTC, jpt-sn commented on tapeagents/llms.py
> +            # reconstructed_prompt_completion = "".join(decoded_prompt_completion_tokens)
I enforced the ruff linter on the ci job instead of the previous flake8 (see `make check-lint`). Those variable were unused.

2025-01-21 17:17 UTC, ollmer approved these changes
LGTM, great work!

2025-01-21 21:13 UTC, merged