Control nodes
ServiceNow/TapeAgents pull request #65
Opened 2024-10-17 19:53 UTC by ollmer

- rewrote gaia, workarena and math agents to the linear node flows
- introduced the control flow node and fixed steps node
- removed monoagents
- removed dated GaiaResults storage format
- updated tests with tapes containing SetNextNode step
- removed `.with_...()` methods from the Agent

2024-10-18 13:02 UTC, rizar requested changes
thanks! I'd like to change two things:

- GuidanceNode -> MonoNode
- let's use absolute node indices to prevent confusion

2024-10-18 13:02 UTC, rizar commented on tapeagents/agent.py
> +        return LLMOutput(role="assistant", content=tape.steps[index].content)
good riddance!

2024-10-19 08:11 UTC, ollmer commented on examples/gaia_agent/agent.py
> +                GaiaNode(name="think_after_observation", guidance=PromptRegistry.think_after_observation, next_node=-1),
Ok!

2024-10-21 14:03 UTC, ollmer commented
@rizar all comments addressed, pleas take a look

2024-10-21 14:06 UTC, rizar commented on tapeagents/nodes.py
> +    A node for simple agents:
```suggestion
    A node for simple monolithic agents:
```

2024-10-21 14:14 UTC, merged