RL training of Llama 3.1 70b on GSM8k
ServiceNow/TapeAgents pull request #78
Opened 2024-10-31 02:42 UTC by AlexPiche

- [x] Launch accelerate job as a subprocess.
- [ ] Single node training with LoRA
- [ ] Multi node trainign with deepspeed

2024-10-31 12:39 UTC, rizar commented
will address #77  and #76

2024-11-05 13:32 UTC, rizar approved these changes
looks good! let me go test this now

2024-11-05 13:32 UTC, rizar commented on tapeagents/finetune/rl/__init__.py
> +    def calculate_reward_with_implicit_kl(row):
this function does not use any variables of the function in which it is located, I'd move it to the top-level. Inner functions are often not so great for readability.

2024-11-05 13:32 UTC, rizar commented on requirements.finetune.txt
> +accelerate==1.0.1
@ollmer objections?

2024-11-05 13:32 UTC, rizar commented on conf/rl_gsm8k.yaml
> +accelerate_cfg_path: conf/deepspeed/accelerate_base.yaml
we should change the name of this config directory to `conf/accelerate`

2024-11-05 13:59 UTC, rizar commented on examples/rl_gsm8k/orchestrate_rl.py
> +            if state["iteration"] % cfg.test_every_n_iterations == 0 and cfg.test_every_n_iterations > 0:
remove before merging :)

2024-11-19 17:33 UTC, rizar requested changes
Looks mostly good! We should not traverse the whole training set every time the script is launched though. 

Note for the re-review:
- check ReLU weights citation 
- check running aggregation of input lengths

2024-11-19 17:33 UTC, rizar commented on tapeagents/finetune/checkpoints.py
> -        if is_rl:
was it a debug hack?

2024-11-19 17:33 UTC, rizar commented on tapeagents/finetune/finetune.py
> +    if accelerator.is_main_process:
You have just made it mandatory to make a full pass over an arbitrarily large training set.... not a great default behavior.

Can you implement this as a running metric in the training loop instead? You can report it every time the gradient accumulation is finished.

2024-11-19 17:33 UTC, rizar commented on tapeagents/finetune/rl/__init__.py
> +    weights = torch.clamp(weights, min=0) if config.relu_weights else weights
where does this trick come from? can you put a paper reference? where do we use it?

2024-11-19 17:33 UTC, rizar commented on tapeagents/finetune/rl/__init__.py
> +    if config.implicit_kl_coef > 0:
This adds negative KL to reward, I suppose. Can we call it `config.reward_minus_kl`?

2024-11-19 17:33 UTC, rizar commented on tapeagents/observe.py
> +_ACTIVE_MANAGER: Optional["SQLiteWriterThread"] = None
```suggestion
_WRITER_THREAD: Optional["SQLiteWriterThread"] = None
```

2024-11-19 18:32 UTC, ollmer commented on requirements.finetune.txt
> +accelerate==1.0.1
No

2024-11-20 16:29 UTC, rizar approved these changes
lgtm!

2024-11-20 16:43 UTC, merged