[WIP] do not modify tape metadata in agent.run()
ServiceNow/TapeAgents pull request #82
Opened 2024-10-31 21:06 UTC by NicolasAG

Before: running `agent.run(tape)` modified inplace the tape metadata passed to agent.run().

Fix: use `model_copy(update=dict(...))` to modify the metadata object.

Also modified: `tape.append(step)` used to set `metadata.n_added_steps` to 1. Changed it to `tape.metadata.n_added_steps + 1`

TODO: add some python tests.

2024-11-04 10:20 UTC, ollmer requested changes
LGTM! But update the `test_append_multiple_steps()` test, please.

2024-11-04 16:40 UTC, ollmer approved these changes

2024-11-04 16:41 UTC, ollmer commented
LGTM! @rizar any comments?

2024-11-04 19:39 UTC, rizar approved these changes
I like this much better, thanks, @NicolasAG !

@ollmer I think we should not copy metadata in `tape.append()`. As we discussed with you before, the purpose of `tape.append()` is to create ephemeral tapes for internal purposes. I think it is safer to wipe the metadata from these tapes. I also suggest we reserve a specific meaning for `n_added_steps` and make it the number of steps that `agent.run()` or `env.react()` added to the tape. `tape.append()` in this case should not set `n_added_steps` at all. 

Let me know if you have objections, @ollmer

2024-11-04 19:43 UTC, merged

2024-11-05 11:36 UTC, ollmer commented
I find it useful in general to have n_added_steps updated by append, as it indicates the number of the most recent steps in the end of the table. But I don't have any example usage for that right now. So I'm ok; let's live with your version for some time and see if we need to change it later.